import Config

config :hmconf, Hmconf.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "mezan",
  database: "hmconf_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hmconf, HmconfWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger,
  level: :info,
  backends: [:console, {LoggerFileBackend, :prod_log}]

# Configure the file logger backend
config :logger, :prod_log,
  path: "log/prod.log",
  level: :info,
  rotation: [size: 10_000_000, keep: 7], # Rotate when file reaches 10MB or daily
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
